title: Dish Anywhere - Your Entertainment Everywhere 
description: Discover endless entertainment with Dish Anywhere. Stream shows, movies, and live TV on any device. Access content, live broadcasts, and manage DVR recordings easily. Entertainment, anywhere.
show_downloads: true
theme: jekyll-theme-cayman
google_analytics: UA-282747729-1
